### ISSUE TITLE
Select an Auth Provider

### ISSUE THREAD

**Issue by reynoldsalec** [lando/desktop#37]
- Security: What does the base platform encryption look like? Can we encrypt values stored along with the user data?
- Ease of use
- Documentation quality
- APIs available for Node/Electron
- Support for other identity providers (aka enterprise compatibility with Okta. Are there other IdPs that we'd want to be compatible with? Active Directory.)

Experiment with implementing the auth solution with the most promising auth provider.

**Comment by labboy0276** [comment]
auth0 still reigns supreme based off others I looked at.

**Comment by labboy0276** [comment]
this has been implemented for the most part, so i will close this out
